@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Sep 03 09:42:37 +0530 2019
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim sr_latch_tb_behav -key {Behavioral:sim_1:Functional:sr_latch_tb} -tclbatch sr_latch_tb.tcl -view C:/Users/Ankit Karan/Desktop/lab2/SR Latch/sr_latch_tb_behav.wcfg -log simulate.log"
call xsim  sr_latch_tb_behav -key {Behavioral:sim_1:Functional:sr_latch_tb} -tclbatch sr_latch_tb.tcl -view C:/Users/Ankit Karan/Desktop/lab2/SR Latch/sr_latch_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
